### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by Zales0123**

### CODE REVIEW

**Comment by pamil** [comment]
Why is it needed?

**Comment by Zales0123** [comment]
To fix tests 😄

**Comment by pamil** [comment]
I'd go for dropping the problematic test instead:

- it's `StringFieldType`, so it shouldn't be expected for it to handle something that can't be cast to string
- its output is rendered directly in the grid HTML, so we need to take care about sanitizing it
- we can't sanitize the output if we just return it
- actually, if you pass something that can't be cast to a string, it'll still fail but in a different place
- even if this technically is a BC break, it'd be a really rare edge-case and we can still make it according to our BC policy (security reasons)

We can add a new test that makes sure that objects with `__toString()` also gets escaped (will be easy to do using anonymous class). What do you think?

**Comment by pamil** [comment]
Fixed in #7.

**Pull request closed without merging**
