### PR TITLE
Process all grid filter, field and driver service tags

### PR DESCRIPTION
**Pull request by vvasiloi**
Fixes https://github.com/Sylius/SyliusGridBundle/issues/22

### CODE REVIEW

**Comment by Zales0123** [comment]
Could you please take a look at the failing tests? As far as I see, it's only coding standards, so running `vendor/bin/ecs check src --fix` should fix them :)

**Comment by vvasiloi** [comment]
@Zales0123 I ran it for the files I changed, the remaining issues are in files outside of the scope of this PR.

**Comment by vvasiloi** [comment]
@Zales0123 I opened a separate PR for that: https://github.com/Sylius/SyliusGridBundle/pull/24

**Comment by vvasiloi** [comment]
Will open a new one from a dedicated branch.

**Pull request closed without merging**
