### PR TITLE
Fix filtering entities with multiple values

### PR DESCRIPTION
**Pull request by loic425**
It fixes the entity filter when you add "multiple" on form options.

```
filters:
    partner:
        type: entity
        [..]
        form_options:
            [..]
            multiple: true
```

### CODE REVIEW

**Comment by loic425** [comment]
@pamil @lchrusciel One of the Travis jobs is queued since 3 hours... I don't know why.

**Comment by loic425** [comment]
> Shouldn't we add some integration tests as well?

Yes, you're right. Should I create a small app like in Sylius Resource bundle?
https://github.com/Sylius/SyliusResourceBundle/tree/master/src/Bundle/test

**Comment by loic425** [comment]
@pamil @lchrusciel Any idea to add some integration tests?

**Comment by lchrusciel** [comment]
Sample setup is already here: https://github.com/Sylius/SyliusGridBundle/blob/master/src/Bundle/Tests/Functional/GridApiTest.php

**Comment by loic425** [comment]
@lchrusciel I found time to add a functional test :)

**Comment by pamil** [comment]
Thanks, Loïc! :1st_place_medal:

**Pull request merged**
