### PR TITLE
Pagerfanta updates

### PR DESCRIPTION
**Pull request by mbabker**
Very simple PR which:

- Updates the used adapter classes to stop using the deprecated classes
- Allows Pagerfanta 3.0

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Michael, 

sorry for lack of activity. Can you extend our workflow to check both versions? Perhaps with --prefer-lowest? Or just bump this dependency to 3.0, as it won't be supported since next year anywya

**Comment by mbabker** [comment]
> Or just bump this dependency to 3.0

Done.  Now blocked by https://github.com/Sylius/SyliusResourceBundle/pull/298 needing to allow 3.0 first 😅

**Comment by lchrusciel** [comment]
Merged, now we need to release ResourceBundle. Perhaps next week

**Comment by lchrusciel** [comment]
Hey Michael,

thanks a lot for your contribution and patience. What you've proposed landed in Grid in #205, therefore I'm closing this PR.

**Pull request closed without merging**
